#!/usr/bin/env python3
"""软著材料版权风险检查（本地、离线）。

三层检查：
  1. 项目层：LICENSE / 包清单 license 字段 / git 远程与提交者 / 常见开源脚手架指纹
  2. 取材层：config 里每个 source_files —— 第三方路径、开源许可证头、他人版权声明、
     仓库/博客链接、“forked from / 参考自”、自动生成标记、AI 生成标记、压缩代码、
     密钥 / 手机号 / 邮箱 / 内网 IP、多份软著之间的取材重叠
  3. 产出层：说明书 / 申请表 / auto-fill 配置 / 源程序 docx·pdf 中的仓库与开源字样、
     敏感信息，以及软件名称 / 版本号 / 著作权人在各材料间是否一致

原则：申报材料中一律不得出现仓库地址与开源信息。
- 自有开源项目（config: self_open_source=true，self_aliases=[GitHub/Gitee 账号、英文名]）：
  许可证头、仓库链接等由 generate_source_docx.py / oss_scrub.py 自动清除；发表状态按“未发表”处理
  （申报的是上架版本，与开源参考代码不同）
- 第三方代码：不删除他人声明，整份文件不取材（提取时自动跳过）
自有代码里的密钥、手机号、邮箱、内网 IP 由 generate_source_docx.py 在提取时脱敏（redact_line）。

用法：
  python3 copyright_check.py --config soft-copyright-materials/ruanzhu.config.json --repo .
  python3 copyright_check.py ... --report 版权风险检查报告.md --fail-on high
  python3 copyright_check.py ... --suggest-config      # 生成剔除高风险文件后的 config 建议稿
"""

import argparse
import json
import re
import subprocess
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from output_names import (manual_pdf_name, source_material_docx_name,
                          source_material_pdf_name, submission_dir)  # noqa: E402
from artifact_manifest import formal_material_paths  # noqa: E402

MISSING_FACT = re.compile(r"^\s*(?:待确认|待填写|待补充|待核验)(?:\s*[（(].*)?\s*$")


def configured_fact(value):
    """Return an actual configured fact, not an old config prompt."""
    text = str(value or "").strip()
    return "" if MISSING_FACT.fullmatch(text) else text

SEV_ORDER = {"high": 0, "medium": 1, "low": 2}
SEV_CN = {"high": "高", "medium": "中", "low": "低"}

# ------------------------------------------------------------------ 规则
THIRD_PARTY_PATH = re.compile(
    r"(?:^|/)(?:node_modules|bower_components|vendor|vendors|third[_-]?party|3rdparty|external|Pods|Carthage"
    r"|\.pnpm|site-packages|dist|build|out|target|\.next|\.nuxt|uni_modules|jspm_packages)/"
    r"|\.min\.(?:js|css)$|(?:^|/)(?:jquery|bootstrap|lodash|echarts|swiper|vue|react)[\w.-]*\.js$", re.I)
GENERATED_PATH = re.compile(
    r"(?:_pb2(?:_grpc)?\.py|\.pb\.(?:go|cc|h)|\.g\.dart|\.freezed\.dart|\.designer\.cs|(?:^|/)R\.java"
    r"|\.generated\.\w+|(?:^|/)(?:package-lock\.json|yarn\.lock|pnpm-lock\.yaml|go\.sum))$", re.I)

TYPE_DECL = re.compile(r"\.d\.ts$", re.I)
# 引擎/框架项目模板自带的版权头：文件是模板生成后二次修改的，声明必须保留
ENGINE_VENDORS = re.compile(r"Egret|Cocos|Chukong|Layabox|LayaAir|Unity Technologies|Epic Games|DCloud"
                            r"|Tencent|Alibaba|Microsoft|Google|JetBrains|Apple Inc", re.I)

LICENSE_TEXT = [
    ("GPL/AGPL（传染性）", r"GNU (?:Affero )?General Public License|SPDX-License-Identifier:\s*A?GPL", "high"),
    ("LGPL", r"GNU Lesser General Public License|SPDX-License-Identifier:\s*LGPL", "high"),
    ("Apache-2.0", r"Licensed under the Apache License|SPDX-License-Identifier:\s*Apache", "high"),
    ("MIT", r"Permission is hereby granted, free of charge|SPDX-License-Identifier:\s*MIT", "high"),
    ("BSD", r"Redistribution and use in source and binary forms|SPDX-License-Identifier:\s*BSD", "high"),
    ("MPL", r"Mozilla Public License|SPDX-License-Identifier:\s*MPL", "high"),
    ("其他 SPDX", r"SPDX-License-Identifier:", "high"),
    ("木兰/国产开源协议", r"木兰宽松许可证|Mulan PSL", "high"),
]
COPYRIGHT_LINE = re.compile(r"(?:Copyright|©|版权所有|\(c\)(?=\s*\d{4}))\s*(?:\(c\)|©)?\s*(?:\d{4}(?:\s*[-–]\s*\d{4})?)?[,\s]*([^\n*/]{2,60})", re.I)
AUTHOR_TAG = re.compile(r"@author\s+([^\s*]{1,40})|^\s*(?:#|//|\*)\s*Author\s*[:：]\s*(\S{1,40})", re.I | re.M)
REPO_URL = re.compile(
    r"https?://(?:www\.)?(?:github\.com|gitlab\.com|gitee\.com|bitbucket\.org|gitcode\.(?:com|net)|coding\.net"
    r"|codeup\.aliyun\.com|sourceforge\.net|raw\.githubusercontent\.com|gist\.github\.com)/[\w./%-]*", re.I)
GENERATED_MARK = re.compile(
    r"auto-?generated|Code generated by|DO NOT EDIT|@generated|This file (?:was|is) (?:automatically )?generated"
    r"|自动生成|请勿手动修改|由工具生成", re.I)
AI_MARK = re.compile(
    r"generated (?:by|with|using) (?:ChatGPT|GPT-?\d|Copilot|Claude|Cursor|Gemini|通义|文心|Kimi|豆包)"
    r"|(?:ChatGPT|Copilot|Claude|Cursor)[- ]generated|AI[- ]generated|由\s*(?:AI|ChatGPT|Copilot|Claude|通义|文心|豆包)\s*生成", re.I)

SECRETS = [
    ("AWS AccessKey", r"\bAKIA[0-9A-Z]{16}\b"),
    ("OpenAI/Anthropic 类密钥", r"\bsk-(?:ant-|proj-)?[A-Za-z0-9_-]{20,}"),
    ("GitHub Token", r"\bgh[pousr]_[A-Za-z0-9]{30,}"),
    ("阿里云 AccessKey", r"\bLTAI[0-9A-Za-z]{12,24}\b"),
    ("私钥", r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"),
    ("JWT", r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
    # 下面两条匹配整个赋值语句，密钥本身放在具名组 v 里：脱敏只替换 v，保留标识符和赋值号。
    # 用字母边界而不是 \b：DB_PASSWORD / MYSQL_ROOT_PASSWORD 这类下划线命名在 \b 下会漏检。
    ("硬编码口令/密钥", r"(?i)(?<![A-Za-z])(?:password|passwd|pwd|secret|api_?key|access_?token|app_?secret)(?![A-Za-z])\s*[:=]\s*['\"](?P<v>[^'\"\s]{6,})['\"]"),
    ("微信 AppSecret", r"(?i)appsecret['\"]?\s*[:=]\s*['\"](?P<v>[0-9a-f]{32})['\"]"),
]
PII = [
    ("手机号", r"(?<!\d)1[3-9]\d{9}(?!\d)"),
    ("邮箱", r"\b[\w.+-]+@[\w-]+\.[\w.-]+\b"),
    ("内网 IP", r"\b(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}\b"),
    ("身份证号", r"(?<!\d)\d{17}[\dXx](?!\d)"),
]
PII_ALLOW = re.compile(r"example\.(?:com|org)|@(?:types|babel|vue|angular|nestjs|param|return|author|see|link|since)\b"
                       r"|noreply|localhost|\.(?:png|jpg|svg|gif|webp)$", re.I)

# 常见开源脚手架 / 商业开源项目指纹（包名、命名空间、独特标识）
SCAFFOLDS = [
    ("RuoYi 若依", r"com\.ruoyi|ruoyi-|RuoYi"),
    ("JeecgBoot", r"org\.jeecg|jeecg-boot|JeecgBoot"),
    ("芋道 yudao", r"cn\.iocoder|yudao-"),
    ("pig", r"com\.pig4cloud"),
    ("mall / mall-swarm", r"com\.macro\.mall"),
    ("eladmin", r"me\.zhengjie"),
    ("renren", r"io\.renren"),
    ("BladeX / SpringBlade", r"org\.springblade"),
    ("litemall", r"org\.linlinjava"),
    ("CRMEB", r"crmeb"),
    ("likeadmin / likeshop", r"likeadmin|likeshop"),
    ("FastAdmin", r"fastadmin"),
    ("vue-element-admin", r"vue-element-admin|PanJiaChen"),
    ("Vben Admin", r"vben-admin|@vben/"),
    ("Ant Design Pro", r"ant-design-pro|@ant-design/pro-"),
    ("vue-pure-admin", r"pure-admin"),
    ("soybean-admin", r"soybean-admin|@soybeanjs/"),
    ("naive-ui-admin", r"naive-ui-admin"),
    ("Halo", r"run\.halo"),
    ("mall4j", r"com\.yami\.shop"),
    ("hello-uniapp 模板", r"hello-uniapp"),
    ("Egret 官方示例", r"egret-examples|EgretExample"),
]
SCAFFOLDS = [(n, re.compile(p, re.I)) for n, p in SCAFFOLDS]

LICENSE_FILES = ("LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "COPYING", "COPYING.md", "NOTICE", "NOTICE.md")


def _value_span(m):
    """密钥值在整段匹配中的位置；模式没有具名组 v 时即整段匹配。"""
    if "v" in m.re.groupindex and m.group("v") is not None:
        return m.span("v")
    return m.span(0)


def _mask_secret(m):
    """裸令牌保留 4 位方案前缀（AKIA/ghp_ 之类），赋值语句只替换引号内的值。"""
    whole, (start, end) = m.group(0), _value_span(m)
    if (start, end) == m.span(0):
        return whole[:4] + "****"
    base = m.start(0)
    return whole[:start - base] + "****" + whole[end - base:]


def secret_hits(text):
    """按位置合并重叠匹配：同一处密钥常同时命中多条规则，只应算一处。"""
    raw = sorted((_value_span(m), name)
                 for name, pat in SECRETS for m in re.finditer(pat, text))
    merged = []
    for (start, end), name in raw:
        if merged and start < merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], end)
            if name not in merged[-1][2]:
                merged[-1][2].append(name)
        else:
            merged.append([start, end, [name]])
    return [(start, end, names) for start, end, names in merged]


def redact_line(line):
    """提取源程序时对自有代码脱敏：只处理密钥与个人信息，不动许可证/版权文字。"""
    for _, pat in SECRETS:
        line = re.sub(pat, _mask_secret, line)
    for name, pat in PII:
        def mask(m, name=name):
            s = m.group(0)
            if PII_ALLOW.search(s):
                return s
            if name == "邮箱":
                return "***@" + s.split("@", 1)[1]
            return s[:3] + "*" * (len(s) - 5) + s[-2:]
        line = re.sub(pat, mask, line)
    return line


# ------------------------------------------------------------------ 结果收集
class Findings:
    def __init__(self):
        self.items = []

    def add(self, sev, layer, where, rule, detail, advice):
        self.items.append({"severity": sev, "layer": layer, "where": where, "rule": rule,
                           "detail": detail[:160], "advice": advice})

    def count(self, sev):
        return sum(1 for i in self.items if i["severity"] == sev)


def mask(s):
    return re.sub(r"[A-Za-z0-9_-]{8,}", lambda m: m.group(0)[:4] + "****", s)


def holder_tokens(holder):
    """著作权人名称的可比对片段：全称、去掉“有限公司”等后缀的简称。"""
    if not holder or holder.startswith("【"):
        return []
    core = re.sub(r"(?:股份)?有限(?:责任)?公司|工作室|科技|信息技术|网络|集团|（.*?）|\(.*?\)", "", holder)
    return [t for t in {holder, core} if len(t) >= 2]


# ------------------------------------------------------------------ 1. 项目层
def git(repo, *args):
    try:
        return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, timeout=20).stdout
    except (OSError, subprocess.TimeoutExpired):
        return ""


def _own_tokens(cfg, repo=None):
    from oss_scrub import own_tokens
    return own_tokens(cfg, repo)


def _is_own(who, tokens):
    return any(t.lower() in who.lower() for t in tokens)


OWN_OSS_ADVICE = "自有开源：材料生成时自动清除（源程序 generate_source_docx.py，说明书 oss_scrub.py）；源程序须取自申报的上架版本"


def check_project(repo, cfg, F):
    tokens = _own_tokens(cfg, repo)
    self_oss = bool(cfg.get("self_open_source"))
    for name in LICENSE_FILES:
        p = repo / name
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")[:6000]
        kind = next((k for k, pat, _ in LICENSE_TEXT if re.search(pat, text, re.I)), "未识别")
        owners = [re.sub(r"^[-–\s]*(?:present|now)?[,\s]*", "", m.group(1)).strip() for m in COPYRIGHT_LINE.finditer(text)]
        own_license = self_oss and all(_is_own(w, tokens) for w in owners if w)
        if own_license:
            F.add("low", "项目", name, f"自有开源项目（{kind}）", "、".join(owners)[:60], OWN_OSS_ADVICE)
            continue
        sev = "high" if "GPL" in kind else "medium"
        F.add(sev, "项目", name, f"项目含开源许可证（{kind}）",
              text.strip().splitlines()[0] if text.strip() else "",
              "若是自己开源的项目：在 config 设 self_open_source=true 并把 GitHub/Gitee 账号、英文名写进 self_aliases；"
              "否则确认权利归属后再申报")
        for who in owners:
            if tokens and who and not _is_own(who, tokens) and not re.search(r"<?year>?|\[yyyy\]|\{\{", who, re.I):
                F.add("high", "项目", name, "LICENSE 中的版权人与申报著作权人不一致", who,
                      "说明项目可能是他人项目的 fork/二次开发；须确认原作者授权，或只申报自己新增的独立部分")
                break

    for manifest in ("package.json", "composer.json", "pyproject.toml", "setup.py", "Cargo.toml", "pom.xml",
                     "build.gradle", "pubspec.yaml", "go.mod"):
        p = repo / manifest
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        head = text[:20000]
        lic = re.search(r"[\"']?license[\"']?\s*[:=]\s*[\"']([^\"']+)|<license>\s*<name>([^<]+)", head, re.I)
        if lic and self_oss:
            F.add("low", "项目", manifest, "包清单声明了开源许可证（自有）", (lic.group(1) or lic.group(2)).strip(),
                  OWN_OSS_ADVICE)
        elif lic:
            F.add("medium", "项目", manifest, "包清单声明了开源许可证", (lic.group(1) or lic.group(2)).strip(),
                  "自有开源项目：设 self_open_source=true 并补 self_aliases；否则确认代码来源")
        for m in re.finditer(r"[\"']?(?:author|authors|contributors)[\"']?\s*[:=]\s*[\[\"']?([^\"'\]\n]{2,80})", head, re.I):
            who = m.group(1).strip()
            if tokens and not _is_own(who, tokens):
                F.add("low", "项目", manifest, "包清单作者与著作权人不同", mask(who),
                      "员工职务作品可以；外部作者需确认权利归属")
                break
        for m in REPO_URL.finditer(head):
            F.add("low" if self_oss else "medium", "项目", manifest, "包清单含代码仓库地址", m.group(0),
                  OWN_OSS_ADVICE if self_oss else "仓库地址不得出现在申报材料中；如为自有仓库，补 self_aliases")
            break
        for sname, pat in SCAFFOLDS:
            if pat.search(head) and not _is_own(sname, tokens):
                F.add("high", "项目", manifest, f"疑似基于开源项目：{sname}", pat.pattern,
                      "只能申报自己独立开发的部分：源码取材排除脚手架原有文件，说明书不要描述脚手架自带功能，名称不要沿用原项目名")

    if (repo / ".git").exists():
        remotes = git(repo, "remote", "-v")
        urls = sorted({l.split()[1] for l in remotes.splitlines() if len(l.split()) > 1})
        for u in urls:
            public = re.search(r"github\.com|gitee\.com|gitlab\.com|gitcode", u, re.I)
            owner = re.search(r"(?:github\.com|gitee\.com|gitlab\.com|gitcode\.(?:com|net))[:/]([\w.-]+)/", u, re.I)
            mine = owner and _is_own(owner.group(1), tokens)
            if public and mine:
                F.add("low", "项目", ".git/config", "自有公开仓库", u, OWN_OSS_ADVICE)
            else:
                F.add("medium" if public else "low", "项目", ".git/config", "git 远程仓库", u,
                      "仓库所有者不在 self_aliases 中：确认是自己的仓库（补 self_aliases）还是他人项目/fork")
        if len([l for l in remotes.splitlines() if l.startswith("upstream")]):
            F.add("high", "项目", ".git/config", "存在 upstream 远程", "upstream",
                  "典型 fork 工作流：须核实上游项目的许可证与原作者权利，只申报自研部分")
        authors = [a for a in git(repo, "log", "--format=%an").splitlines() if a]
        if authors:
            uniq = sorted(set(authors))
            F.add("low", "项目", "git log", f"提交者 {len(uniq)} 人 / 提交 {len(authors)} 次",
                  "、".join(uniq[:8]) + ("…" if len(uniq) > 8 else ""),
                  "核对提交者是否均为著作权人或其员工/受托方；有外部贡献者需有书面授权")
        first = git(repo, "log", "--reverse", "--format=%s", "-n", "1").strip()
        if re.search(r"initial commit from|from template|clone|fork|import from|init from", first, re.I):
            F.add("medium", "项目", "git log", "首个提交疑似从模板/他人项目导入", first,
                  "确认初始代码来源与授权")


# ------------------------------------------------------------------ 2. 取材层
def check_sources(repo, cfg, F):
    holder_tok = _own_tokens(cfg, repo)
    self_oss = bool(cfg.get("self_open_source"))
    owner = defaultdict(list)
    bad_files = set()
    for proj in cfg.get("projects", []):
        for rel in proj.get("source_files", []):
            owner[rel].append(proj.get("name", proj.get("id")))
    for rel, names in owner.items():
        if len(names) > 1:
            F.add("high", "取材", rel, "同一源文件被多份软著取材", "、".join(names),
                  "黄金原则 2：每个文件只能归属一份软著")
            bad_files.add(rel)

    for rel in owner:
        where = rel
        if THIRD_PARTY_PATH.search(rel):
            F.add("high", "取材", where, "第三方/构建产物路径", rel, "从 source_files 中剔除，改选自研目录下的文件")
            bad_files.add(rel)
        if TYPE_DECL.search(rel):
            F.add("low", "取材", where, "类型声明文件（.d.ts）", rel,
                  "只有声明、没有业务逻辑，第三方 SDK 的声明文件更不应取材；建议换成实现文件")
        if GENERATED_PATH.search(rel):
            F.add("medium", "取材", where, "工具生成文件", rel, "生成代码不体现独创性，建议剔除")
            bad_files.add(rel)
        p = repo / rel
        if not p.exists():
            F.add("medium", "取材", where, "文件不存在", str(p), "检查 --repo 路径或更新 source_files")
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        lines = text.splitlines()
        if lines and (max(len(l) for l in lines) > 1000 or sum(len(l) for l in lines) / len(lines) > 250):
            F.add("high", "取材", where, "压缩/打包代码", f"平均行长 {sum(len(l) for l in lines) // len(lines)}",
                  "非手写源码，剔除")
            bad_files.add(rel)
        head = "\n".join(lines[:60])
        head_owners = [re.sub(r"^[-–\s]*(?:present|now)?[,\s]*", "", m.group(1)).strip()
                       for m in COPYRIGHT_LINE.finditer(head)]
        own_head = holder_tok and all(_is_own(w, holder_tok) for w in head_owners if w.strip(" .,")) and \
            (head_owners or self_oss)
        for kind, pat, sev in LICENSE_TEXT:
            if re.search(pat, head, re.I) and own_head:
                F.add("low", "取材", f"{where}:1-60", f"自有许可证头（{kind}）", re.search(pat, head, re.I).group(0),
                      "提取时自动整块删除")
                break
            if re.search(pat, head, re.I):
                vendor = ENGINE_VENDORS.search(head)
                advice = ("文件由引擎/框架模板生成（" + vendor.group(0) + "）后修改：原声明必须保留，"
                          "不宜作为源程序材料，换成其他完全自研的文件" if vendor else
                          "这是第三方或已开源代码：不得删除许可证头冒充自研，应从 source_files 剔除")
                F.add(sev, "取材", f"{where}:1-60", f"文件头含开源许可证（{kind}）", re.search(pat, head, re.I).group(0),
                      advice)
                bad_files.add(rel)
                break
        for m in COPYRIGHT_LINE.finditer(head):
            who = re.sub(r"^[-–\s]*(?:present|now)?[,\s]*", "", m.group(1)).strip()
            if re.search(r"^\s*$|^[\W\d]+$", who):
                continue
            if not holder_tok or not _is_own(who, holder_tok):
                sev = "high" if holder_tok else "medium"
                F.add(sev, "取材", where, "文件含他人（或未核实）版权声明", who,
                      "版权人不是申报主体：剔除该文件；若就是本公司的旧名/英文名，在 config 的 copyright_holder 核对后忽略")
                if holder_tok:
                    bad_files.add(rel)
                break
        from oss_scrub import REF_URL, REF_WORDS
        ref_words = re.compile(REF_WORDS, re.I)
        for no, line in enumerate(lines, 1):
            loc = f"{where}:{no}"
            for m in REPO_URL.finditer(line):
                repo_owner = re.search(r"\.(?:com|org|net)/([\w.-]+)/", m.group(0))
                if repo_owner and _is_own(repo_owner.group(1), holder_tok):
                    F.add("low", "取材", loc, "代码中含自有仓库链接", m.group(0), "提取时自动清除")
                else:
                    F.add("medium", "取材", loc, "代码中含他人仓库链接", m.group(0),
                          "提取时自动清除链接；但要确认这段代码是否取自该仓库，是则换文件")
            for m in REF_URL.finditer(line):
                F.add("medium", "取材", loc, "代码引用博客/问答来源", m.group(0),
                      "提取时自动删除该地址；但该段可能摘自网络，须确认改写程度，或换文件取材")
            if ref_words.search(line):
                F.add("medium", "取材", loc, "注释写明代码来源", line.strip()[:80],
                      "提取时自动删除该注释；但须核实原作者与许可，照搬的代码应换文件")
            if GENERATED_MARK.search(line) and no <= 30:
                F.add("medium", "取材", loc, "自动生成代码标记", line.strip()[:80], "生成代码建议剔除")
                bad_files.add(rel)
            if AI_MARK.search(line):
                F.add("medium", "取材", loc, "AI 生成标记", line.strip()[:80],
                      "如实评估人工修改程度；材料中不宜保留该注释的同时声称全部独立手写")
            for _start, _end, names in secret_hits(line):
                # 先脱敏再做显示截断：mask() 只缩短长标识符，单用会把口令前 4 位写进报告。
                F.add("high", "取材", loc, f"敏感信息：{'／'.join(names)}",
                      mask(redact_line(line.strip())[:80]),
                      "立即轮换该密钥；提取时自动脱敏（generate_source_docx.py 默认开启）")
            for name, pat in PII:
                for m in re.finditer(pat, line):
                    if not PII_ALLOW.search(m.group(0)):
                        F.add("low", "取材", loc, f"个人信息：{name}", mask(m.group(0)), "提取时自动脱敏")
        for m in AUTHOR_TAG.finditer(head):
            who = (m.group(1) or m.group(2) or "").strip()
            if who and holder_tok and not any(t in who for t in holder_tok):
                F.add("low", "取材", where, "@author 与著作权人不同", who,
                      "员工/外包作者需确认职务作品或委托开发协议")
                break
        for sname, pat in SCAFFOLDS:
            if pat.search(head) or pat.search(rel):
                F.add("high", "取材", where, f"取自开源项目：{sname}", pat.pattern, "剔除，改选自研文件")
                bad_files.add(rel)
                break
    # 提取时会被自动跳过的第三方文件：不会进入材料，降为中风险，只提示补选文件
    from oss_scrub import third_party_reasons
    auto_skip = set()
    for rel in owner:
        p = repo / rel
        if p.exists() and third_party_reasons(rel, p.read_text(encoding="utf-8", errors="ignore"), holder_tok):
            auto_skip.add(rel)
    for item in F.items:
        f = item["where"].split(":")[0]
        if item["layer"] == "取材" and f in auto_skip and item["severity"] == "high" and "多份软著" not in item["rule"]:
            item["severity"] = "medium"
            item["advice"] = "提取时自动跳过，不进入材料；请从 source_files 移除并补选自研文件，保证行数"
    return bad_files


# ------------------------------------------------------------------ 3. 产出层
def material_text(p):
    from aigc_rules import pdf_text, split_docx
    if p.suffix == ".pdf":
        return pdf_text(p)
    if p.suffix == ".docx":
        return "\n".join(b.text for b in split_docx(p))
    return p.read_text(encoding="utf-8", errors="ignore")


def _contains_material_value(text, value):
    """PDF 文本提取可能插入空格或兼容字符，匹配时做 NFKC + 空白归一化。"""
    normalize = lambda s: re.sub(r"\s+", "", unicodedata.normalize("NFKC", str(s))).casefold()
    return normalize(value) in normalize(text)


def check_materials(root, cfg, F):
    holder = configured_fact(cfg.get("copyright_holder", ""))
    for proj in cfg.get("projects", []):
        d = root / proj["id"]
        if not d.exists():
            continue
        source_dir = d / "源程序提取"
        final_dir = submission_dir(d)
        # 有正式材料清单时只检查清单列出的提交件，避免旧版/兼容目录污染结果。
        # 清单尚未生成时保留旧版兼容扫描，保证 Step 5（生成清单之前）仍可预检。
        formal = formal_material_paths(d)
        if formal:
            files = [d / "软件说明书.md", d / "申请表填报文案.md", d / "auto-fill" / "config.json"]
            role_by_path = {}
            for role, path in formal.items():
                files.append(path)
                role_by_path[path.absolute()] = role
        else:
            files = [d / "软件说明书.md", d / "申请表填报文案.md", d / "auto-fill" / "config.json",
                     final_dir / manual_pdf_name(proj), d / manual_pdf_name(proj),
                     d / "软件说明书.pdf", d / "软件文档.pdf"]
            files += [final_dir / source_material_pdf_name(proj),
                      source_dir / source_material_pdf_name(proj),
                      source_dir / source_material_docx_name(proj)]
            files += sorted(source_dir.glob("*源程序鉴别材料-*.pdf")) if source_dir.exists() else []
            files += sorted(source_dir.glob("*源程序鉴别材料-*.docx")) if source_dir.exists() else []
            role_by_path = {}
        seen_text = {}
        seen_source = {}
        for f in files:
            if not f.exists():
                continue
            try:
                text = material_text(f)
            except SystemExit as e:
                F.add("low", "产出", str(f), "无法读取", str(e), "安装 pypdf 后重试")
                continue
            seen_text[f.name] = text
            rel = f.absolute().relative_to(root.absolute())
            # 不能只判断“源程序”三个字：新命名是“简称-端类型源码.pdf/docx”。
            # 优先使用清单角色，其次用目录和两套历史命名兼容判断。
            is_source = (role_by_path.get(f.absolute()) == "programPdf"
                         or f.parent.name == "源程序提取"
                         or "源程序" in f.name or "源码" in f.name)
            seen_source[f.name] = is_source
            for m in REPO_URL.finditer(text):
                F.add("high", "产出", str(rel), "材料中出现代码仓库地址", m.group(0),
                      "申报材料一律不得出现仓库地址：清除后重新生成")
            for sname, pat in SCAFFOLDS:
                m = pat.search(text)
                if m and not is_source:
                    F.add("high", "产出", str(rel), f"材料提到开源项目：{sname}", m.group(0),
                          "说明书/申请表只描述自研功能，不写所基于的开源项目；是否可申报先核实授权")
            from oss_scrub import ANY_REPO, OSS_COMMENT, OSS_SENTENCE
            words = OSS_COMMENT if is_source else OSS_SENTENCE
            seen_words = set()
            for m in words.finditer(text):
                if m.group(0).lower() in seen_words:
                    continue
                seen_words.add(m.group(0).lower())
                ctx = text[max(0, m.start() - 15): m.end() + 15].replace("\n", " ")
                F.add("high", "产出", str(rel), f"开源痕迹「{m.group(0)}」", ctx,
                      "申报材料一律不得出现：源程序重新运行 generate_source_docx.py；说明书/申请表运行 oss_scrub.py --apply")
            for m in ANY_REPO.finditer(text):
                if not REPO_URL.fullmatch(m.group(0)):
                    F.add("high", "产出", str(rel), "材料中出现徽章/包平台/仓库地址", m.group(0), "同上，清除后重新生成")
            kinds = sorted({n for _s, _e, names in secret_hits(text) for n in names})
            if kinds:
                F.add("high", "产出", str(rel), f"材料含敏感信息：{'／'.join(kinds)}", "",
                      "重新提取（开启脱敏）后再渲染")
            for name, pat in PII:
                hits = [m.group(0) for m in re.finditer(pat, text) if not PII_ALLOW.search(m.group(0))]
                if hits:
                    F.add("medium" if not is_source else "low", "产出", str(rel), f"材料含{name} {len(hits)} 处",
                          mask(hits[0]), "联系人信息只填在申请表，不写进说明书/源程序")
        # 一致性：名称 / 版本 / 著作权人
        name, ver = proj.get("name", ""), proj.get("version", "V1.0")
        for fname, text in seen_text.items():
            if seen_source.get(fname, False):
                continue
            if name and not _contains_material_value(text, name):
                F.add("high", "产出", f"{proj['id']}/{fname}", "材料中找不到软件全称", name, "各材料的软件全称必须完全一致")
            # 软件说明书和源码 PDF 的标题允许使用简称，且正文不强制展示版本号；
            # 版本一致性只在申请表文案和 auto-fill 配置中核对。
            if ver and ver not in text and fname in {"申请表填报文案.md", "config.json"}:
                F.add("medium", "产出", f"{proj['id']}/{fname}", "材料中找不到版本号", ver, "核对版本号一致")
            if fname == "申请表填报文案.md" and holder and holder not in text:
                F.add("high", "产出", f"{proj['id']}/{fname}", "申请表著作权人与 config 不一致", holder, "核对著作权人全称")
        cfgjson = d / "auto-fill" / "config.json"
        if cfgjson.exists():
            try:
                af = json.loads(cfgjson.read_text(encoding="utf-8"))
                sw = af.get("step2_basic", {}).get("softwareName", "")
                if sw and name and sw != name:
                    F.add("high", "产出", f"{proj['id']}/auto-fill/config.json", "填表软件名称与说明书不一致",
                          f"{sw} ≠ {name}", "改成完全一致")
            except json.JSONDecodeError:
                pass


# ------------------------------------------------------------------ 输出
def render(F, cfg, bad_files):
    rows = sorted(F.items, key=lambda i: (SEV_ORDER[i["severity"]], i["layer"], i["where"]))
    holder = configured_fact(cfg.get("copyright_holder", "")) or "未填写"
    out = ["# 版权风险检查报告", "",
           f"> 著作权人：{holder}　｜　"
           f"高 {F.count('high')} ／ 中 {F.count('medium')} ／ 低 {F.count('low')}",
           "> 本报告只做线索排查，不构成法律意见；高风险项处理完再进入 PDF 渲染与填表。", ""]
    if bad_files:
        out += ["## 建议从 source_files 剔除", "", "| 文件 |", "| --- |"] + [f"| `{f}` |" for f in sorted(bad_files)]
        out += ["", "用 `--suggest-config` 生成剔除后的配置建议稿，补足行数后再重新提取源程序。", ""]
    # 同一文件同一规则的逐行命中合并展示
    grouped = defaultdict(list)
    for r in rows:
        key = (r["severity"], r["layer"], r["where"].split(":")[0], r["rule"])
        grouped[key].append(r)
    for sev in ("high", "medium", "low"):
        keys = [k for k in grouped if k[0] == sev]
        if not keys:
            continue
        out += [f"## {SEV_CN[sev]}风险（{sum(len(grouped[k]) for k in keys)}）", "",
                "| 层 | 位置 | 问题 | 线索 | 处理建议 |", "| --- | --- | --- | --- | --- |"]
        for k in keys:
            items = grouped[k]
            locs = [i["where"] for i in items]
            if len(locs) == 1:
                where = locs[0]
            elif ":" in locs[0]:
                where = f"{k[2]}（{len(locs)} 处，行 " + "、".join(l.split(":")[-1] for l in locs[:5]) + "）"
            else:
                where = f"{k[2]}（{len(locs)} 处）"
            detail = "；".join(dict.fromkeys(i["detail"] for i in items))[:160]
            detail = detail.replace("|", "\\|").replace("\n", " ")
            out.append(f"| {k[1]} | `{where}` | {k[3]} | {detail} | {items[0]['advice']} |")
        out.append("")
    if not rows:
        out.append("未发现版权风险线索。")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="软著材料版权风险检查")
    ap.add_argument("--config", default="soft-copyright-materials/ruanzhu.config.json")
    ap.add_argument("--repo", default=".", help="被申报项目的源码根目录")
    ap.add_argument("--report", help="Markdown 报告输出路径（默认 <output_root>/版权风险检查报告.md）")
    ap.add_argument("--json", help="JSON 结果输出路径")
    ap.add_argument("--skip", nargs="*", default=[], choices=["project", "sources", "materials"])
    ap.add_argument("--fail-on", choices=["high", "medium"], help="存在该级别及以上风险时退出码 1")
    ap.add_argument("--suggest-config", action="store_true",
                    help="写出 ruanzhu.config.suggested.json（剔除高风险文件，不覆盖原配置）")
    args = ap.parse_args()

    cfg_path = Path(args.config)
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    repo = Path(args.repo).resolve()
    root = Path(cfg.get("output_root", "soft-copyright-materials"))
    F = Findings()
    bad = set()
    if "project" not in args.skip:
        check_project(repo, cfg, F)
    if "sources" not in args.skip:
        bad = check_sources(repo, cfg, F)
    if "materials" not in args.skip:
        check_materials(root, cfg, F)

    report = Path(args.report) if args.report else root / "版权风险检查报告.md"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(render(F, cfg, bad), encoding="utf-8")
    if args.json:
        Path(args.json).write_text(json.dumps(F.items, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.suggest_config and bad:
        sug = json.loads(json.dumps(cfg))
        for proj in sug.get("projects", []):
            before = len(proj.get("source_files", []))
            proj["source_files"] = [f for f in proj.get("source_files", []) if f not in bad]
            proj["_removed_by_copyright_check"] = before - len(proj["source_files"])
        out = cfg_path.with_name("ruanzhu.config.suggested.json")
        out.write_text(json.dumps(sug, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"配置建议稿：{out}（确认后手动替换原配置，并补充取材文件保证行数）")
    print(f"高 {F.count('high')} / 中 {F.count('medium')} / 低 {F.count('low')}  报告：{report}")
    if args.fail_on:
        limit = SEV_ORDER[args.fail_on]
        if any(SEV_ORDER[i["severity"]] <= limit for i in F.items):
            sys.exit(1)


if __name__ == "__main__":
    main()
